# ╔══════════════════════════════════════════════════════════════════╗
# ║   MODULE: GKPLattices                                             ║
# ║                                                                  ║
# ║   GKP lattice primitives in the qqpp convention, and the         ║
# ║   trivial classical-LDLC → GKP construction M = √d · H.          ║
# ╚══════════════════════════════════════════════════════════════════╝

"""
    GKPLattices

Lattice primitives for multi-mode GKP codes, in the **qqpp** coordinate
convention `x = (q₁…qₙ, p₁…pₙ)` with symplectic form

    J = [0  Iₙ; -Iₙ  0]  =  [0 1; -1 0] ⊗ Iₙ.

A GKP code on `n` modes is a full-rank lattice in `R^{2n}` with generator
matrix `M` (`2n×2n`, **rows are stabilizer generators**; the lattice is the
set of integer row-combinations `aᵀM`). The symplectic Gram matrix
`A = M J Mᵀ` must be integer; the logical dimension is `K = |det M|`.

This module provides the symplectic form, the Gram matrix, the symplectic
dual generator, an exact integer determinant, and the trivial construction
`M = √d · H` from a classical low-density lattice code `H` generated by
`LatticeDecoder.classical_ldlc`.
"""
module GKPLattices

using LinearAlgebra: I, det
import LatticeDecoder

export symplectic_form, gkp_gram, dual_generator, det_exact,
       is_integer_matrix, trivial_gkp_from_ldlc

"""
    symplectic_form(n::Integer; T::Type=Int) -> Matrix{T}

The `2n×2n` symplectic form in the qqpp convention,
`J = [0 1; -1 0] ⊗ Iₙ`. Pass `T=BigInt` (or `Rational{BigInt}`) when the
result feeds exact arithmetic.
"""
symplectic_form(n::Integer; T::Type=Int) = kron(T[0 1; -1 0], Matrix{T}(I, n, n))

"""
    gkp_gram(M::AbstractMatrix{<:Integer}) -> Matrix

Symplectic Gram matrix `A = M J Mᵀ` of a GKP generator `M` (size `2n×2n`).
Errors unless `A` is antisymmetric (it is automatically integer for integer
`M`). Entries stay small for the trivial LDLC construction, but callers that
need canonical forms should pass `BigInt.(A)` to `symplectic_basis_over_ZZ`.
"""
function gkp_gram(M::AbstractMatrix{<:Integer})
    r, c = size(M)
    @assert r == c && iseven(r) "M must be square of even size (got $(size(M)))"
    n = r ÷ 2
    J = symplectic_form(n; T=eltype(M))
    A = M * J * transpose(M)
    @assert A == -transpose(A) "Gram matrix must be antisymmetric"
    return A
end

"""
    dual_generator(M) -> Matrix{Rational{BigInt}}

Generator of the symplectic dual lattice, `M⊥ = J A⁻¹ M` with `A = M J Mᵀ`,
computed exactly over `Rational{BigInt}`. The rows of `M⊥` generate the group
of logical + stabilizer displacements; `L(M⊥) ⊇ L(M)` and the quotient encodes
the logical operators. Accepts integer or rational `M`.
"""
function dual_generator(M::AbstractMatrix{<:Union{Integer,Rational}})
    r, c = size(M)
    @assert r == c && iseven(r) "M must be square of even size (got $(size(M)))"
    n = r ÷ 2
    Mr = Rational{BigInt}.(M)
    J = symplectic_form(n; T=Rational{BigInt})
    A = Mr * J * transpose(Mr)
    return J * inv(A) * Mr
end

"""
    det_exact(M::AbstractMatrix{<:Integer}) -> BigInt

Exact determinant of an integer matrix, computed over `Rational{BigInt}`
(never through `Float64`). Used only in assertions/tests — the pipeline reads
`|det M| = 2ℓ = dₙ` directly off the invariant factors.
"""
det_exact(M::AbstractMatrix{<:Integer})::BigInt = numerator(det(Rational{BigInt}.(M)))

"""
    is_integer_matrix(A::AbstractMatrix{<:AbstractFloat}; atol=1e-8) -> Bool

`true` iff every entry of `A` is within `atol` of an integer.
"""
is_integer_matrix(A::AbstractMatrix{<:AbstractFloat}; atol::Real=1e-8) =
    all(x -> abs(x - round(x)) <= atol, A)

"""
    trivial_gkp_from_ldlc(d::Integer, n::Integer; max_tries=5000) -> Matrix{Int}

Trivial GKP generator `M = √d · H` (size `2n×2n`), where `H` is a `d`-regular
magic-square classical LDLC check matrix. For the default weights `√d · H` has
integer entries (`±1` and `±√d`), which is asserted before rounding.

This mirrors `LatticeDecoder.classical_ldlc(d, 2n)` but uses its building blocks
(`init_p_mat`, `loop_removal!`, `build_H_mat`) directly so that **each attempt is
a single loop-removal pass** with a caller-controlled budget: `classical_ldlc`
hardcodes 1000 internal attempts and only *warns* on non-convergence, whereas
`loop_removal!` returns the convergence flag, letting us discard-and-retry
cleanly and fail fast. Only **4-cycle-free** (converged) draws are accepted, up
to `max_tries`, after which an error is thrown.

Convergence is stochastic and strongly `n`-dependent: the per-attempt success
rate is essentially zero for very small `n` (≲10) and rises with `n`, so this is
practical for `n ≳ 13` (matching the regime of the original experiments) and the
generation scripts. It draws from the **global** RNG — seed it (`Random.seed!`)
before calling for reproducibility.
"""
function trivial_gkp_from_ldlc(d::Integer, n::Integer; max_tries::Integer=20000)
    d >= 2 || throw(ArgumentError("d must be ≥ 2 (got $d)"))
    n >= 1 || throw(ArgumentError("n must be ≥ 1 (got $n)"))
    di, N = Int(d), 2 * Int(n)
    weights = Float64[1.0; fill(1 / sqrt(di), di - 1)]   # classical_ldlc default weights
    s = sqrt(float(di))
    for _ in 1:max_tries
        P = LatticeDecoder.init_p_mat(di, N)
        LatticeDecoder.loop_removal!(P, di, N) || continue   # 4-cycle-free only
        H = LatticeDecoder.build_H_mat(di, N, weights, P)
        Mfloat = s .* H
        is_integer_matrix(Mfloat) || continue                # guard (holds for default weights)
        return round.(Int, Mfloat)
    end
    error("trivial_gkp_from_ldlc: could not obtain a 4-cycle-free LDLC for " *
          "(d=$d, n=$n) within $max_tries attempts (loop-removal convergence is " *
          "very low for small n — try larger n)")
end

end # module GKPLattices
